## Chocolate Sales

![chocolate gold](https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg)
<sup>Pixabay, pexels.com</sup>

In [1]:
import pandas as pd

## Cleaning Dataset

In [3]:
df = pd.read_csv("Chocolate Sales (2).csv")
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   object
 1   Country        3282 non-null   object
 2   Product        3282 non-null   object
 3   Date           3282 non-null   object
 4   Amount         3282 non-null   object
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), object(5)
memory usage: 154.0+ KB

In [ ]:
# removing "$"
df["Amount"] = (
    df["Amount"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)
# converting date to datetime
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# creating date features
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month Label"] = df["Date"].dt.strftime("%Y-%m")
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)

In [7]:
# saving clean dataset
df.to_csv("chocolate_sales_clean.csv", index=False)

In [8]:
choc_df = pd.read_csv("chocolate_sales_clean.csv")
choc_df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped,Year,Month,Month Label,Quarter
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180,2022,1,2022-01,Q1
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94,2022,8,2022-08,Q3
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91,2022,7,2022-07,Q3
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342,2022,4,2022-04,Q2
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184,2022,2,2022-02,Q1

In [20]:
print(f" Sales Persons: {choc_df['Sales Person'].unique()}\n")
print(f" Countries: {choc_df['Country'].unique()}\n")
print(f" Products: {choc_df['Product'].unique()}\n")
print(f" Range: {choc_df['Date'].min()} - {choc_df['Date'].max()}")

 Sales Persons: ['Jehu Rudeforth' 'Van Tuxwell' 'Gigi Bohling' 'Jan Morforth' 'Oby Sorrel'
 'Gunar Cockshoot' 'Brien Boise' 'Rafaelita Blaksland' 'Barr Faughny'
 'Mallorie Waber' 'Karlen McCaffrey' "Marney O'Breen" 'Beverie Moffet'
 'Roddy Speechley' 'Curtice Advani' 'Husein Augar' 'Kaine Padly'
 'Dennison Crosswaite' "Wilone O'Kielt" 'Andria Kimpton' 'Kelci Walkden'
 'Camilla Castle' 'Madelene Upcott' 'Dotty Strutley' 'Ches Bonnell']

 Countries: ['UK' 'India' 'Australia' 'New Zealand' 'USA' 'Canada']

 Products: ['Mint Chip Choco' '85% Dark Bars' 'Peanut Butter Cubes'
 'Smooth Sliky Salty' '99% Dark & Pure' 'After Nines' '50% Dark Bites'
 'Orange Choco' 'Eclairs' 'Drinking Coco' 'Organic Choco Syrup'
 'Milk Bars' 'Spicy Special Slims' 'Fruit & Nut Bars' 'White Choc'
 'Manuka Honey Choco' 'Almond Choco' 'Raspberry Choco'
 'Choco Coated Almonds' "Baker's Choco Chips" 'Caramel Stuffed Bars'
 '70% Dark Bites']

 Range: 2022-01-03 - 2024-08-31